### ISSUE TITLE
Conda install fails on macOSX

### ISSUE THREAD

**Issue by michaelaye** [USGS-Astrogeology/autocnet#245]
Created its own conda env as advised, using Python 3.6 and added conda channels as advised in the readme.
But there's no package called `autocnet-dev` nor `autocnet` on any of those channels:

```
(autocnet) └─❱❱❱ conda install -c usgs-astrogeology autocnet-dev                        1 ⏎  +7863 14:21 ❰─┘
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - autocnet-dev

Current channels:

  - https://conda.anaconda.org/usgs-astrogeology/osx-64
  - https://conda.anaconda.org/usgs-astrogeology/noarch
  - https://conda.anaconda.org/menpo/osx-64
  - https://conda.anaconda.org/menpo/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/osx-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/osx-64
  - https://repo.anaconda.com/pkgs/pro/noarch
  - https://conda.anaconda.org/NSIDC/osx-64
  - https://conda.anaconda.org/NSIDC/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by jlaura** [comment]
This should be fixed by #247. Please let us know if it is now.

**Comment by michaelaye** [comment]
No change here. the package `autocnet-dev` is still not on the usgs-astrogeology/osx-64 channel.

**Comment by jlaura** [comment]
Please use `autocnet`. `autocent-dev` has been removed.

**Comment by michaelaye** [comment]
that did it.
